#!/bin/bash

__version__='0.2'

if [ "$1" == '-h' ] || [ "$1" == '--help' ]; then
	echo -en """
HELP SCREEN PLACE HOLDER
"""
elif [ "$1" == '-v' ] || [ "$1" == '--version' ]; then
	echo -en """
BooeySay's Script Generator v"$__version__"
"""
elif [ "$1" == '-x' ] || [ "$1" == '--executable' ]; then
	filename=$2
	if [ -f "$filename" ]; then
		echo -e "error: filename already exiats"
		unset filename
		exit
	else
		echo -e "#!/usr/bin/env python3\n" > "$filename"
		if [ "$1" == '-x' ]; then
			chmod u+x "$filename"
		fi
		echo -en """
Script successfully created and modified to be an executable.

[ Hit [Enter] to open script in nano, or [Q] to Quit ]

"""
		read
		case $REPLY in
			'')
				nano +3,0 "$filename"
				;;
			'q'|'Q')
				echo -en """
Exiting ...
"""
#				exit
				;;
		esac
	fi
	unset filename REPLY
else
	filename=$1
	if [ -f "$filename" ]; then
		echo -e "error: filename already exiats"
		unset filename
		exit
	else
		echo -e "#!/usr/bin/env python3\n" > "$filename"
		nano +3,0 "$filename"
		unset filename
		exit
	fi
fi
